name: Release Branch Policy Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr.base.ref.startsWith('release/')) {
              const labels = pr.labels.map(l => l.name);
              if (!labels.includes('release-fix')) {
                core.setFailed('Missing release-fix label');
              }
              if (!pr.body.includes('Forward-Port')) {
                core.setFailed('Missing Forward-Port Plan');
              }
            }
